### ISSUE TITLE
Parameter subtypes aren't being converted to Blueprint-compatible types

### ISSUE THREAD

**Issue by joeporpeglia** [vimeo/mill#147]
> @api-data more_videos.video_uris (array&lt;uri&gt;) - The videos in this collection that will be played once the video ends.

When this is generated into a Blueprint file, `array[uri]` is generated: 

```
- `after` (object) - What goes after the video.
    - `more_videos` (object) - What videos the user sees after the main video has ended.
        - `video_uris` (array[uri]) - The videos in this collection that will be played 
            once the video ends.
```

`uri` should be translated into `string`

**Comment by erunion** [comment]
Resolved in Mill 4.
