### ISSUE TITLE
Grouping classes in single `use` statement leads to errors being discovered 

### ISSUE THREAD

**Issue by edubrovs** [vimeo/mill#192]
If I have a use statement that groups multiple classes in one line then, sometimes I see an error for that file at https://github.com/vimeo/mill/blob/master/src/Config.php#L1018

$file (argument) should be: 
full path to file 
$namespace should evaluate to:
path to file without the class name 
$class should evaluate to:
the class name 

The problem is that $class evaluates to an empty string. 

As a result, ultimately the error is thrown at https://github.com/vimeo/mill/blob/master/src/Reader.php#L20 `Class xxx does not exist`

Note: 
From what I’ve observed once before having `use` in the grouping format fails if there is some docs error in the file — it’s not due to that `use` statement itself. 
In another controller file, it turned out to be an `api-contentType` doc error.. however that error was only caught when I changed `use` to the grouping format.

**Comment by edubrovs** [comment]
cc @erunion

**Comment by erunion** [comment]
Seems like the config `getClassFQNFromFile` isn't properly handling PHP 7 merged `use` statements.

**Comment by edubrovs** [comment]
Just want to note that grouping multiple classes isn't consistently erroring.
