### ISSUE TITLE
Surface resource and resource action descriptions in API Blueprint files

### ISSUE THREAD

**Issue by erunion** [vimeo/mill#29]
Not exactly sure how we're going to handle this because those descriptions can contain Markdown, and it'll be very difficult to merge that with the Markdown in the Blueprint files. Nonetheless we should figure something out, even if it's just converting Markdown headers into bold elements or something.

**Comment by Dashron** [comment]
Wanted to know what the spec says, and found this: https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#description

looks like we're fine as long as it doesn't clash with existing apib reserved words

**Comment by erunion** [comment]
Rad, that'll make this a lot easier.

**Comment by erunion** [comment]
This was done as part of the [2.0 work](https://github.com/vimeo/mill/pull/77).
