### ISSUE TITLE
Endpoint parameters are unalphabetized.

### ISSUE THREAD

**Issue by erunion** [vimeo/mill#37]
```
...
* @api-param:public {string} name (optional) The new title for the video
* @api-param:public {string} license [by|by-sa|by-nd|by-nc|by-nc-sa|by-nc-nd|cc0] (optional) Set the Creative Commons license
* @api-param:public {string} description (optional) The new description for the video
...
```

When generated into Blueprint, or even just from the generator array, these parameters are in the order that they were typed. 

To keep things clean, and friendly to the person actually consuming documentation, Mill should alphabetize (recursively if necessary on dot-notation field) parameters.

**Comment by Dashron** [comment]
:+1:
