### ISSUE TITLE
@api-warning support on representations

### ISSUE THREAD

**Issue by erunion** [vimeo/mill#70]
There are some instances in the Vimeo API where we have data within a representation that depends upon a service call, and that call may fail from time to time. The problem right now is that when that call fails, we don't then want the entire endpoint to fail.

Instead, we've come up with a solution to return an array of "warnings" with information on what data in the representation we were unable to fill out for the developer.

The way to document this, I believe, is with a new `@api-warning` annotation. It'll look the same as an `@api-throws`, just without an HTTP status code.

```php
@api-warning \Warning\Representation (\Warning\Error:CODE) Some warning message.
```

This annotation will only be available on representations:

```php
/**
 * @api-data metadata.connections.watched_videos (object) - Information about the 
 *      videos this user has watched.
 * @api-see \App\Representation\Connection::create metadata.connections.watched_videos
 * @api-warning \App\Representation\Warning 
 *      (\App\Warnings\PlayProgress::WATCHED_VIDEOS_UNAVAILABLE) Watched videos 
 *      are currently unavailable.
 */
```

For configuration, I think we can go with the same setup that we have for error representations since this is a little similar:

```xml
<representations>
    <filter>
        ...
    </filter>

    <errors>
        ...
    </errors>
    
    <warnings>
        <class name="\App\Representation\Warning" method="create" />
    </warnings>
</representations>
```

--- 

* [ ] Build an `@api-warning` annotation to be used within representations.
  * [ ] This is an optional annotation.
  * [ ] There should not be a limit on the amount of warnings that a dataset can have.
  * [ ] As we have with `@api-throws` annotations, there should be validation in place to verify that the attached warning representation is valid, and the (required) error code is present.
    * [ ] As is the case with `@api-throws`, error codes should be able to be strings or a FQN static callable. If it is not callable, we should throw a validation error.
* [ ] Replicate the same system that we have in place for error representation configs for warnings.
* [ ] In the generated API Blueprint file, surface any representation warnings up to the `+ Response` and display them in a bulleted list similar to how we're currently surfacing multiple `@api-throws` and error codes.

**Comment by agilefox** [comment]
Looks like we're moving away from the idea that we will not return the key, and will instead return the cached data and a warning. 

I'm not sure if that has implications here.

**Comment by erunion** [comment]
I think we'll still want to document the warning, so we can probably still use this.

**Comment by erunion** [comment]
We've decided to not go through with this kind of system for now.
